/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Company model module.
 * @module model/Company
 * @version 0.0.0
 */
export class Company {
  /**
   * Constructs a new <code>Company</code>.
   * Company Model
   * @alias module:model/Company
   * @class
   * @param companyName {String} 
   */
  constructor(companyName) {
    this.companyName = companyName;
  }

  /**
   * Constructs a <code>Company</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Company} obj Optional instance to populate.
   * @return {module:model/Company} The populated <code>Company</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Company();
      if (data.hasOwnProperty('company_id'))
        obj.companyId = ApiClient.convertToType(data['company_id'], 'Number');
      if (data.hasOwnProperty('company_name'))
        obj.companyName = ApiClient.convertToType(data['company_name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} companyId
 */
Company.prototype.companyId = undefined;

/**
 * @member {String} companyName
 */
Company.prototype.companyName = undefined;

